{{- $clustername := .Values.cluster.name }}
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  labels: "test-templates"
  annotations: "test-annotation"
  name: {{ $clustername }}
  namespace: fleet-default
spec:
  cloudCredentialSecretName: {{ .Values.cloudCredentialSecretName }}
  kubernetesVersion: v1.31.2+rke2r1
  {{- /* localClusterAuthEndpoint:
    caCerts: ''
    enabled: false
    fqdn: ''
  */ -}}
  machinePools:
    - controlPlaneRole: true
      etcdRole: true
      workerRole: true
      quantity: 1
      name: {{ $clustername }}-controlplane
      machineConfigRef:
        kind: VmwarevsphereConfig
        name: {{ $clustername }}-controlplane
      paused: false
      displayName: {{ $clustername }}-controlplane
{{- /*
     - controlPlaneRole: false
      etcdRole: false
      workerRole: true
      quantity: 1
      name: {{ $clustername }}-worker
      machineConfigRef:
        kind: VmwarevsphereConfig
        name: {{ $clustername }}-worker
      paused: false
      displayName: {{ $clustername }}-worker 
*/ -}}
  rkeConfig:
    chartValues:
      rke2-cilium:
        hubble:
          enabled: true
          relay:
            enabled: true
          ui:
            enabled: true
        ipv6:
          enabled: true
        k8sServiceHost: 127.0.0.1
        k8sServicePort: '6443'
        kubeProxyReplacement: true
        bgpControlPlane:
          enabled: true
    machineGlobalConfig:
      cluster-cidr: 10.42.0.0/16,fd00:10:42::/56
      cni: cilium
      disable-kube-proxy: true
      etcd-expose-metrics: false
      service-cidr: 10.96.0.0/16,fd00:10:96::/112
