{{- $clustername := .Values.cluster.name }}
apiVersion: rke-machine-config.cattle.io/v1
kind: VmwarevsphereConfig
metadata:
  name: {{ $clustername }}-controlplane
  namespace: fleet-default
cfgparam: {{ $nodepool.cfgparam }}
cloneFrom: {{ $nodepool.cloneFrom }}
# cloudConfig: |
# {{ $nodepool.cloudConfig | indent 2 }}
#cloudinit: {{ $nodepool.cloudinit }}
#contentLibrary: {{ $nodepool.contentLibrary }}
cpuCount: {{ $nodepool.cpuCount | quote }}
creationType: {{ $nodepool.creationType }}
#customAttribute: {{ $nodepool.customAttribute }}
datacenter: {{ $nodepool.datacenter }}
datastore: {{ $nodepool.datastore }}
#datastoreCluster: {{ $nodepool.datastoreCluster }}
diskSize: {{ $nodepool.diskSize | quote }}
folder: {{ $nodepool.folder }}
hostsystem: {{ $nodepool.hostsystem }}
memorySize: {{ $nodepool.memorySize | quote }}
network: {{ $nodepool.network }}
pool: {{ $nodepool.pool }}
#sshPort: {{ $nodepool.sshPort | quote }}
#sshUser: {{ $nodepool.sshUser }}
#sshUserGroup: {{ $nodepool.sshUserGroup }}
#tag: {{ $nodepool.tag }}
vappIpallocationpolicy: {{ $nodepool.vappIpallocationpolicy }}
vappIpprotocol: {{ $nodepool.vappIpprotocol }}
vappProperty: {{ $nodepool.vappProperty }}
vappTransport: {{ $nodepool.vappTransport }}
vcenter: {{ $nodepool.vcenter }}
vcenterPort: {{ $nodepool.vcenterPort | quote }}
