{{- $clustername := .Values.cluster.name }}
apiVersion: rke-machine-config.cattle.io/v1
kind: VmwarevsphereConfig
metadata:
  name: {{ $clustername }}-controlplane
  namespace: fleet-default
cfgparam: ["disk.enableUUID: TRUE"]
cloneFrom: "/LBNL/vm/Templates/Rancher/kapil-test"
cpuCount: 4
creationType: "template"
datacenter: "/LBNL"
datastore: "/LBNL/datastore/vsanDatastore_lbl"
diskSize: 100
folder: "/LBNL/vm"
hostsystem: "Any"
memorySize: 8192
network: "ds06.198.128.131.1-24"
pool: "/LBNL/host/lbnl-clstr4/Resources/RPn_RancherDev"
vappIpallocationpolicy: "fixedAllocated"
vappIpprotocol: "IPv4"
vappProperty: ["ipaddress=ip:ds06.198.128.131.1-24", "gateway=$${gateway:ds06.198.128.131.1-24}", "dns=$${dns:ds06.198.128.131.1-24}"]
vappTransport: "com.vmware.guestInfo"
vcenter: "vcenter-west1.es.net"
vcenterPort: 443
